services:
  chat-server:
    image: signalr-chatserver
    container_name: chatserver
    build:
      context: ./Backend.Chat
      dockerfile: Backend.Chat/Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - app_network

  chat-client:
    image: signalr-chat-client
    container_name: chatclient
    build:
      context: ./Frontend.Chat/signalr-chat-ui
      dockerfile: Dockerfile
      args:
        - VITE_CHATHUB_URL=/chatHub
    expose:
      - "5173"
    depends_on:
      - chat-server
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: chat-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-server
      - chat-client
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
